name: pdf_image_renderer
description: A package that allows fast and simple rendering of pdfs using the native renderers of the OS.
version: 0.1.1+1
homepage: https://github.com/cloudacy/pdf_image_renderer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.packages.pdf_image_renderer
        pluginClass: PdfImageRendererPlugin
      ios:
        pluginClass: PdfImageRendererPlugin
