name: pdf_image_renderer
description: A package that allows fast and simple rendering of pdfs using the native renderers of the OS.
version: 0.4.0
homepage: https://github.com/cloudacy/pdf_image_renderer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.pdf_image_renderer
        pluginClass: PdfImageRendererPlugin
      ios:
        pluginClass: PdfImageRendererPlugin
